version: '3.9'
services:
  nginx:
    image: nginx:stable-alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    restart: unless-stopped
    depends_on:
      - app
    networks:
      - nginx-network
  app:
    image: app
    volumes:
      - ./Apps/Online/:/etc/Apps/Online
    build:
      context: "./Apps/Online"
      dockerfile: Dockerfile
    expose:
      - 5000
    restart: unless-stopped
    networks:
      - nginx-network
networks:
  nginx-network:
    driver: bridge